### ISSUE TITLE
Allow for custom metadata path

### ISSUE THREAD

**Issue by teolemon** [ashutoshgngwr/validate-fastlane-supply-metadata#2]
### What
- [ ] I have fastlane data for both versions (iOS and Android) of Open Food Facts in a single repository, and the ability to set a custom metadata path would be awesome. 
Currently the action fails because it expects the metadata folder to be called metadata and not metadata-android.
metadata_path "./fastlane/metadata-android"
metadata_path "./fastlane/metadata-ios"

**Comment by ashutoshgngwr** [comment]
I just published v2 release. `fastlaneDir` option now expects the full path to the Android metadata directory (default is `./fastlane/metadata/android`). Can you please test it and let me know if the release works? I cannot bump it in my own project ATM.

**Comment by octoshrimpy** [comment]
sadly this flag is not working as expected. see: 
https://github.com/octoshrimpy/quik/blob/master/.github/workflows/build-and-release.yml 
and 
https://github.com/octoshrimpy/quik/actions/runs/11452935737/job/31865102655

**Comment by ashutoshgngwr** [comment]
@octoshrimpy Not sure what's going on, but, your action ran with fastlaneDir set to its default value: https://github.com/octoshrimpy/quik/actions/runs/11452935737/job/31865102655#step:6:3

**Comment by octoshrimpy** [comment]
Looks like it uses the artifacts of that run, instead of the current-state of the repo. upon next triggers of the action (not manual reruns) the flag worked correctly. it still failed, but that's some other reason, as I can see in the logs it used the proper path.

**Comment by octoshrimpy** [comment]
![image](https://github.com/user-attachments/assets/cd0244be-7f23-43eb-8b38-430958067a86)
![image](https://github.com/user-attachments/assets/001f9f94-4dcd-424b-ad2e-7847d6667969)
I think I set everything up correctly, but it did not work as expected: 
https://github.com/octoshrimpy/quik/actions/runs/11453553082/job/31866359784

**Comment by ashutoshgngwr** [comment]
@octoshrimpy The `metadata` directory doesn't exist because you skip the checkout step in your release job.

**Comment by octoshrimpy** [comment]
I'm fairly new to this, and unsure what you mean. could you teach/show me?

**Comment by ashutoshgngwr** [comment]
@octoshrimpy Add this step from your apk job to your release job, before the metadata step: https://github.com/octoshrimpy/quik/actions/runs/11453553082/workflow#L15-L16
